nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8080'] # URL de la PWA
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
